[package]
name = "rspamd-tg-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
rspamd-client = { version = "0.1", features = ["async"] }
tokio = { version = "1", features = ["full"] }
teloxide = { version = "0.14.1" }
pretty_env_logger = "0.5.0"
log = "0.4"
dotenv = "0.15"
